use crate::models::{JobStatus, Severity};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseHistoryEntry {
    pub phase: String,
    pub started_at: DateTime<Utc>,
    pub ended_at: DateTime<Utc>,
    pub duration_sec: f64,
    pub outcome: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Finding {
    pub id: String,
    pub agent_source: String,
    pub title: String,
    pub description: String,
    pub severity: Severity,
    pub cvss_vector: Option<String>,
    pub cvss_score: Option<f64>,
    pub evidence: Option<String>,
    pub remediation: Option<String>,
    pub cwe_id: Option<String>,
    pub owasp_category: Option<String>,
    pub confidence: Option<String>,
    pub scanner_name: Option<String>,
    pub scanner_mode: Option<String>,
    pub file_path: Option<String>,
    pub line_number: Option<i32>,
    pub route: Option<String>,
    pub metadata_json: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AuditState {
    pub job_id: String,
    pub user_id: String,
    pub repo_url: String,
    pub repo_branch: String,
    pub repo_owner: String,
    pub repo_name: String,
    pub github_access_token: String,
    pub github_token_scopes: Vec<String>,
    pub created_at: DateTime<Utc>,
    pub custom_email: String,
    pub current_phase: String,
    pub status: JobStatus,
    pub phase_history: Vec<PhaseHistoryEntry>,
    pub clone_path: String,
    pub tech_stack: Vec<String>,
    pub entry_points: Vec<String>,
    pub dependency_manifests: Vec<String>,
    pub repo_security: serde_json::Value,
    pub threat_model: serde_json::Value,
    pub sbom: serde_json::Value,
    pub dependency_vulns: Vec<Finding>,
    pub iac_findings: Vec<Finding>,
    pub api_surface: Vec<serde_json::Value>,
    pub route_risk_summary: serde_json::Value,
    pub sbom_components: Vec<serde_json::Value>,
    pub dependency_graph: serde_json::Value,
    pub vulnerable_components: Vec<serde_json::Value>,
    pub cicd_findings: Vec<Finding>,
    pub container_findings: Vec<Finding>,
    pub authz_findings: Vec<Finding>,
    pub static_findings: Vec<Finding>,
    pub semgrep_findings: Vec<Finding>,
    pub secret_findings: Vec<Finding>,
    pub secret_history_findings: Vec<Finding>,
    pub bandit_findings: Vec<Finding>,
    pub cve_matches: Vec<serde_json::Value>,
    pub normalized_findings: Vec<serde_json::Value>,
    pub sandbox_container_id: String,
    pub sandbox_target_ip: String,
    pub sandbox_ready: bool,
    pub open_ports: Vec<serde_json::Value>,
    pub api_endpoints: Vec<String>,
    pub tls_issues: Vec<serde_json::Value>,
    pub dynamic_findings: Vec<Finding>,
    pub exploit_proofs: Vec<Finding>,
    pub deduplicated_findings: Vec<Finding>,
    pub false_positives: Vec<String>,
    pub attack_chains: Vec<serde_json::Value>,
    pub remediations: Vec<serde_json::Value>,
    pub attack_graph: serde_json::Value,
    pub remediation_plan: serde_json::Value,
    pub remediation_tasks: Vec<serde_json::Value>,
    pub validated_findings: Vec<Finding>,
    pub correlation_report: Vec<HashMap<String, serde_json::Value>>,
    pub scored_findings: Vec<Finding>,
    pub security_score: Option<f64>,
    pub risk_summary: serde_json::Value,
    pub confidence_summary: HashMap<String, serde_json::Value>,
    pub report_pdf_url: String,
    pub report_delivered: bool,
    pub github_issue_created: bool,
    pub github_pr_created: bool,
    pub github_pr_url: String,
    pub github_branch: String,
    pub github_mcp_logs: Vec<String>,
    pub google_agent_delivered: bool,
    pub google_agent_pr_risks_analyzed: bool,
    pub google_agent_logs: Vec<String>,
    pub google_agent_risk_report: HashMap<String, serde_json::Value>,
    pub errors: Vec<serde_json::Value>,
    pub retry_counts: HashMap<String, i32>,
    pub scanner_execution: HashMap<String, serde_json::Value>,
    pub scan_plan: Option<HashMap<String, serde_json::Value>>,
    pub max_scan_duration_sec: i64,
    pub budget_remaining_usd: f64,
}
