"""add_missing_user_columns

Revision ID: 33d7e9f3e8eb
Revises: a1b2c3d4e5f6
Create Date: 2026-06-29 00:17:09.390469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d7e9f3e8eb'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    # Drop column auto_push from audit_jobs if it exists
    if 'audit_jobs' in tables:
        columns = {column["name"] for column in inspector.get_columns("audit_jobs")}
        if 'auto_push' in columns:
            op.drop_column('audit_jobs', 'auto_push')

    # Alter findings.metadata_json if findings table and column exist (non-SQLite only)
    if bind.dialect.name != 'sqlite' and 'findings' in tables:
        columns = {column["name"] for column in inspector.get_columns("findings")}
        if 'metadata_json' in columns:
            op.alter_column('findings', 'metadata_json',
                       existing_type=sa.TEXT(),
                       type_=sa.String(),
                       existing_nullable=True)

    if 'users' in tables:
        columns = {column["name"] for column in inspector.get_columns("users")}
        
        # Add is_active if not exists
        if 'is_active' not in columns:
            op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
            
        # Alter columns if they exist (non-SQLite only)
        if bind.dialect.name != 'sqlite':
            for col_name in ['github_token_updated_at', 'terms_accepted_at', 'first_login_at', 'last_login_at', 'last_logout_at']:
                if col_name in columns:
                    existing_type = postgresql.TIMESTAMP() if bind.dialect.name == 'postgresql' else sa.DateTime()
                    op.alter_column('users', col_name,
                               existing_type=existing_type,
                               type_=sa.DateTime(timezone=True),
                               existing_nullable=True)

        # Drop index ix_users_email_lower_unique if it exists
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes('users')]
        except Exception:
            indexes = []
        if 'ix_users_email_lower_unique' in indexes:
            op.drop_index(op.f('ix_users_email_lower_unique'), table_name='users', postgresql_where='(email IS NOT NULL)')

        # Drop auto_email_reports if it exists
        if 'auto_email_reports' in columns:
            op.drop_column('users', 'auto_email_reports')

        # Create foreign key constraint if roles table exists and users doesn't already have FK
        if 'roles' in tables:
            # SQLite does not support adding constraints directly, but Alembic op.create_foreign_key handles it or ignores on SQLite
            try:
                op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
            except Exception:
                pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_email_reports', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')  # type: ignore
    op.create_index(op.f('ix_users_email_lower_unique'), 'users', [sa.literal_column('lower(email::text)')], unique=True, postgresql_where='(email IS NOT NULL)')
    op.alter_column('users', 'last_logout_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'first_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'terms_accepted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'github_token_updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'is_active')
    op.alter_column('findings', 'metadata_json',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('audit_jobs', sa.Column('auto_push', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
